# Generated by Django 5.0.1 on 2024-02-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='city',
            field=models.CharField(default='latur', max_length=15),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
        migrations.AlterModelTable(
            name='studentmodel',
            table='students',
        ),
    ]
